import fs from 'node:fs';
import path from 'node:path';
import { readJsonFile } from '../fs-json.js';
import { AssetMetaSchema } from '../types/index.js';
import type { IconRegistry } from '../types/index.js';

type RegistryIcon = IconRegistry['icons'][number];

function escapeForTs(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/** AUTO-GENERATED icons.manifest.ts per projectSlug (import in app + Storybook). */
export function writeIconsManifest(
  projectSlug: string,
  slugDir: string,
  icons: RegistryIcon[],
  iconsRoot: string,
): void {
  const entries = icons.map((icon) => {
    const metaFile = path.join(iconsRoot, icon.relativePath, 'meta.json');
    const meta = readJsonFile(metaFile, AssetMetaSchema);
    const constName = icon.name.replace(/[^a-zA-Z0-9]/g, '') || 'Icon';
    const png = `./${icon.iconSlug}/icon.png`;
    const webp = `./${icon.iconSlug}/icon.webp`;
    return { icon, meta, constName, png, webp };
  });

  const assetImports = entries
    .map(
      ({ constName, png, webp }) =>
        `import png_${constName} from '${png}';\nimport webp_${constName} from '${webp}';`,
    )
    .join('\n');

  const bySlugBody = entries
    .map(({ icon, meta, constName }) => {
      return `  '${escapeForTs(icon.iconSlug)}': {
    png: png_${constName},
    webp: webp_${constName},
    meta: ${JSON.stringify(meta)} as const,
  }`;
    })
    .join(',\n');

  const content = `/**
 * AUTO-GENERATED by Synaptik publish. Do not edit manually.
 * Import in product code: import { iconsBySlug } from './icons.manifest';
 */
${assetImports}

export const projectSlug = '${escapeForTs(projectSlug)}' as const;

export const iconsBySlug = {
${bySlugBody}
} as const;

export type GeneratedIconSlug = keyof typeof iconsBySlug;

export function getGeneratedIcon(slug: GeneratedIconSlug) {
  return iconsBySlug[slug];
}
`;

  fs.writeFileSync(path.join(slugDir, 'icons.manifest.ts'), content, 'utf8');
}
