/**
 * AUTO-GENERATED by Synaptik publish. Do not edit manually.
 */
import type { StoryObj } from '@storybook/react';

export default {
  title: 'Generated Icons/agriculture-technology',
  parameters: { layout: 'padded' },
};

type Story = StoryObj;

import png_Co2PoteriMassyPriKhranenii from './co2-poteri-massy-pri-khranenii/icon.png';
import png_DannyeVPlatformu from './dannye-v-platformu/icon.png';
import png_DinamikaPoMesyatsam from './dinamika-po-mesyatsam/icon.png';
import png_EtilenKhranenieIDozarivanie from './etilen-khranenie-i-dozarivanie/icon.png';
import png_IzmerenieMikroklimata from './izmerenie-mikroklimata/icon.png';
import png_MikroklimatUsloviyaKhraneniya from './mikroklimat-usloviya-khraneniya/icon.png';
import png_NevernyjMomentProdazhi from './nevernyj-moment-prodazhi/icon.png';
import png_NevernyyMomentProdazhi from './nevernyy-moment-prodazhi/icon.png';
import png_Ozonirovanie from './ozonirovanie/icon.png';
import png_ParametryStoimosti from './parametry-stoimosti/icon.png';
import png_ParametryUrozhaya from './parametry-urozhaya/icon.png';
import png_Poteri1217 from './poteri-12-17/icon.png';
import png_ProrastanieISozrevanie from './prorastanie-i-sozrevanie/icon.png';
import png_SokhranostUrozhaya from './sokhranost-urozhaya/icon.png';
import png_UsushkaIPorcha from './usushka-i-porcha/icon.png';

const META_Co2PoteriMassyPriKhranenii = {"name":"Co2PoteriMassyPriKhranenii","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"CO₂: потери массы при хранении","promptHash":"6dbacf4098df0f14","sessionId":"8e2f70a2","cardId":"co2-poteri-massy-pri-khranenii","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"co2-poteri-massy-pri-khranenii","publishedAt":"2026-06-02T08:20:26.555Z"} as const;
const META_DannyeVPlatformu = {"name":"DannyeVPlatformu","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Данные в платформу","promptHash":"0e2d83118a2d726f","sessionId":"8e2f70a2","cardId":"dannye-v-platformu","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"dannye-v-platformu","publishedAt":"2026-06-02T08:22:14.367Z"} as const;
const META_DinamikaPoMesyatsam = {"name":"DinamikaPoMesyatsam","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Динамика по месяцам","promptHash":"78b2592561661d47","sessionId":"8e2f70a2","cardId":"dinamika-po-mesyatsam","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"dinamika-po-mesyatsam","publishedAt":"2026-06-02T08:20:20.773Z"} as const;
const META_EtilenKhranenieIDozarivanie = {"name":"EtilenKhranenieIDozarivanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Этилен: хранение и дозаривание","promptHash":"72a65aa7a2d58c52","sessionId":"8e2f70a2","cardId":"etilen-khranenie-i-dozarivanie","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"etilen-khranenie-i-dozarivanie","publishedAt":"2026-06-02T08:20:23.569Z"} as const;
const META_IzmerenieMikroklimata = {"name":"IzmerenieMikroklimata","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Измерение микроклимата","promptHash":"6a66308e507223a7","sessionId":"8e2f70a2","cardId":"izmerenie-mikroklimata","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"izmerenie-mikroklimata","publishedAt":"2026-06-02T08:20:32.046Z"} as const;
const META_MikroklimatUsloviyaKhraneniya = {"name":"MikroklimatUsloviyaKhraneniya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Микроклимат: условия хранения","promptHash":"1764106dc3399701","sessionId":"8e2f70a2","cardId":"mikroklimat-usloviya-khraneniya","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"mikroklimat-usloviya-khraneniya","publishedAt":"2026-06-02T08:20:29.627Z"} as const;
const META_NevernyjMomentProdazhi = {"name":"NevernyjMomentProdazhi","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"96a17153fbb95099","sessionId":"1b081e1c","cardId":"nevernyj-moment-prodazhi","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"nevernyj-moment-prodazhi","publishedAt":"2026-06-02T11:30:54.288Z","falSeed":948839033} as const;
const META_NevernyyMomentProdazhi = {"name":"NevernyyMomentProdazhi","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"ec0074111a2310f0","sessionId":"8e2f70a2","cardId":"nevernyy-moment-prodazhi","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"nevernyy-moment-prodazhi","publishedAt":"2026-06-02T08:20:12.057Z"} as const;
const META_Ozonirovanie = {"name":"Ozonirovanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонирование","promptHash":"4289d7018fab046f","sessionId":"8e2f70a2","cardId":"ozonirovanie","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"ozonirovanie","publishedAt":"2026-06-02T08:21:19.094Z"} as const;
const META_ParametryStoimosti = {"name":"ParametryStoimosti","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры стоимости","promptHash":"d54ee12e4fe1f9ed","sessionId":"8e2f70a2","cardId":"parametry-stoimosti","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"parametry-stoimosti","publishedAt":"2026-06-02T08:20:17.826Z"} as const;
const META_ParametryUrozhaya = {"name":"ParametryUrozhaya","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры урожая","promptHash":"230dbf24abbeec76","sessionId":"1b081e1c","cardId":"parametry-urozhaya","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"parametry-urozhaya","publishedAt":"2026-06-02T12:35:57.130Z","falSeed":111511914} as const;
const META_Poteri1217 = {"name":"Poteri1217","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Потери 12–17%","promptHash":"6fef87a24dd3d2ed","sessionId":"1b081e1c","cardId":"poteri-12-17","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"poteri-12-17","publishedAt":"2026-06-02T12:35:23.168Z","falSeed":742163273} as const;
const META_ProrastanieISozrevanie = {"name":"ProrastanieISozrevanie","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"C","sourceCard":"Прорастание и созревание","promptHash":"566cf0a0dad0ed35","sessionId":"1b081e1c","cardId":"prorastanie-i-sozrevanie","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"prorastanie-i-sozrevanie","publishedAt":"2026-06-02T14:22:39.367Z","falSeed":1557094316} as const;
const META_SokhranostUrozhaya = {"name":"SokhranostUrozhaya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сохранность урожая","promptHash":"d2f8f1a846858d90","sessionId":"8e2f70a2","cardId":"sokhranost-urozhaya","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"sokhranost-urozhaya","publishedAt":"2026-06-02T08:21:49.253Z"} as const;
const META_UsushkaIPorcha = {"name":"UsushkaIPorcha","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"C","sourceCard":"Усушка и порча","promptHash":"5d4994773734b86c","sessionId":"1b081e1c","cardId":"usushka-i-porcha","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"usushka-i-porcha","publishedAt":"2026-06-02T12:35:34.447Z","falSeed":1904074101} as const;

const SRC_Co2PoteriMassyPriKhranenii = png_Co2PoteriMassyPriKhranenii;
const SRC_DannyeVPlatformu = png_DannyeVPlatformu;
const SRC_DinamikaPoMesyatsam = png_DinamikaPoMesyatsam;
const SRC_EtilenKhranenieIDozarivanie = png_EtilenKhranenieIDozarivanie;
const SRC_IzmerenieMikroklimata = png_IzmerenieMikroklimata;
const SRC_MikroklimatUsloviyaKhraneniya = png_MikroklimatUsloviyaKhraneniya;
const SRC_NevernyjMomentProdazhi = png_NevernyjMomentProdazhi;
const SRC_NevernyyMomentProdazhi = png_NevernyyMomentProdazhi;
const SRC_Ozonirovanie = png_Ozonirovanie;
const SRC_ParametryStoimosti = png_ParametryStoimosti;
const SRC_ParametryUrozhaya = png_ParametryUrozhaya;
const SRC_Poteri1217 = png_Poteri1217;
const SRC_ProrastanieISozrevanie = png_ProrastanieISozrevanie;
const SRC_SokhranostUrozhaya = png_SokhranostUrozhaya;
const SRC_UsushkaIPorcha = png_UsushkaIPorcha;

const ALL_ICON_ITEMS = [
  { name: 'Co2PoteriMassyPriKhranenii', slug: 'co2-poteri-massy-pri-khranenii', src: SRC_Co2PoteriMassyPriKhranenii, meta: META_Co2PoteriMassyPriKhranenii },
  { name: 'DannyeVPlatformu', slug: 'dannye-v-platformu', src: SRC_DannyeVPlatformu, meta: META_DannyeVPlatformu },
  { name: 'DinamikaPoMesyatsam', slug: 'dinamika-po-mesyatsam', src: SRC_DinamikaPoMesyatsam, meta: META_DinamikaPoMesyatsam },
  { name: 'EtilenKhranenieIDozarivanie', slug: 'etilen-khranenie-i-dozarivanie', src: SRC_EtilenKhranenieIDozarivanie, meta: META_EtilenKhranenieIDozarivanie },
  { name: 'IzmerenieMikroklimata', slug: 'izmerenie-mikroklimata', src: SRC_IzmerenieMikroklimata, meta: META_IzmerenieMikroklimata },
  { name: 'MikroklimatUsloviyaKhraneniya', slug: 'mikroklimat-usloviya-khraneniya', src: SRC_MikroklimatUsloviyaKhraneniya, meta: META_MikroklimatUsloviyaKhraneniya },
  { name: 'NevernyjMomentProdazhi', slug: 'nevernyj-moment-prodazhi', src: SRC_NevernyjMomentProdazhi, meta: META_NevernyjMomentProdazhi },
  { name: 'NevernyyMomentProdazhi', slug: 'nevernyy-moment-prodazhi', src: SRC_NevernyyMomentProdazhi, meta: META_NevernyyMomentProdazhi },
  { name: 'Ozonirovanie', slug: 'ozonirovanie', src: SRC_Ozonirovanie, meta: META_Ozonirovanie },
  { name: 'ParametryStoimosti', slug: 'parametry-stoimosti', src: SRC_ParametryStoimosti, meta: META_ParametryStoimosti },
  { name: 'ParametryUrozhaya', slug: 'parametry-urozhaya', src: SRC_ParametryUrozhaya, meta: META_ParametryUrozhaya },
  { name: 'Poteri1217', slug: 'poteri-12-17', src: SRC_Poteri1217, meta: META_Poteri1217 },
  { name: 'ProrastanieISozrevanie', slug: 'prorastanie-i-sozrevanie', src: SRC_ProrastanieISozrevanie, meta: META_ProrastanieISozrevanie },
  { name: 'SokhranostUrozhaya', slug: 'sokhranost-urozhaya', src: SRC_SokhranostUrozhaya, meta: META_SokhranostUrozhaya },
  { name: 'UsushkaIPorcha', slug: 'usushka-i-porcha', src: SRC_UsushkaIPorcha, meta: META_UsushkaIPorcha }
] as const;

const BLOCK_0_ITEMS = [
  { slug: 'co2-poteri-massy-pri-khranenii', src: SRC_Co2PoteriMassyPriKhranenii, meta: META_Co2PoteriMassyPriKhranenii },
  { slug: 'etilen-khranenie-i-dozarivanie', src: SRC_EtilenKhranenieIDozarivanie, meta: META_EtilenKhranenieIDozarivanie },
  { slug: 'mikroklimat-usloviya-khraneniya', src: SRC_MikroklimatUsloviyaKhraneniya, meta: META_MikroklimatUsloviyaKhraneniya },
] as const;

const BLOCK_1_ITEMS = [
  { slug: 'dannye-v-platformu', src: SRC_DannyeVPlatformu, meta: META_DannyeVPlatformu },
  { slug: 'izmerenie-mikroklimata', src: SRC_IzmerenieMikroklimata, meta: META_IzmerenieMikroklimata },
  { slug: 'ozonirovanie', src: SRC_Ozonirovanie, meta: META_Ozonirovanie },
  { slug: 'sokhranost-urozhaya', src: SRC_SokhranostUrozhaya, meta: META_SokhranostUrozhaya },
] as const;

const BLOCK_2_ITEMS = [
  { slug: 'dinamika-po-mesyatsam', src: SRC_DinamikaPoMesyatsam, meta: META_DinamikaPoMesyatsam },
  { slug: 'parametry-stoimosti', src: SRC_ParametryStoimosti, meta: META_ParametryStoimosti },
  { slug: 'parametry-urozhaya', src: SRC_ParametryUrozhaya, meta: META_ParametryUrozhaya },
] as const;

const BLOCK_3_ITEMS = [
  { slug: 'nevernyj-moment-prodazhi', src: SRC_NevernyjMomentProdazhi, meta: META_NevernyjMomentProdazhi },
  { slug: 'nevernyy-moment-prodazhi', src: SRC_NevernyyMomentProdazhi, meta: META_NevernyyMomentProdazhi },
  { slug: 'poteri-12-17', src: SRC_Poteri1217, meta: META_Poteri1217 },
  { slug: 'prorastanie-i-sozrevanie', src: SRC_ProrastanieISozrevanie, meta: META_ProrastanieISozrevanie },
  { slug: 'usushka-i-porcha', src: SRC_UsushkaIPorcha, meta: META_UsushkaIPorcha },
] as const;

export const AllIcons: Story = {
  name: 'All icons',
  render: () => {
    const items = ALL_ICON_ITEMS;
    return (
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16, padding: 16 }}>
        {items.map((item) => (
          <div key={item.name} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
            <img src={item.src} alt={item.name} width={80} height={80} style={{ objectFit: 'contain' }} />
            <div style={{ fontSize: 11, marginTop: 8 }}>{item.name}</div>
          </div>
        ))}
      </div>
    );
  },
};

export const ByBlocks: Story = {
  name: 'By blocks',
  render: () => (
    <div style={{ padding: 16 }}>
      <>
      <section key="block-0" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Контролируйте хранилище не выходя из дома</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_0_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-1" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Как работает генератор</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_1_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-2" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Рассчитайте стоимость урожая и выгоду от хранения</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_2_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-3" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Отсутствие контроля = упущенная выгода</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_3_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      </>
    </div>
  ),
};

export const Icon_Co2PoteriMassyPriKhranenii: Story = {
  name: 'co2-poteri-massy-pri-khranenii',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Co2PoteriMassyPriKhranenii} alt="Co2PoteriMassyPriKhranenii" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Co2PoteriMassyPriKhranenii</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Co2PoteriMassyPriKhranenii, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_DannyeVPlatformu: Story = {
  name: 'dannye-v-platformu',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_DannyeVPlatformu} alt="DannyeVPlatformu" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>DannyeVPlatformu</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_DannyeVPlatformu, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_DinamikaPoMesyatsam: Story = {
  name: 'dinamika-po-mesyatsam',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_DinamikaPoMesyatsam} alt="DinamikaPoMesyatsam" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>DinamikaPoMesyatsam</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_DinamikaPoMesyatsam, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_EtilenKhranenieIDozarivanie: Story = {
  name: 'etilen-khranenie-i-dozarivanie',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_EtilenKhranenieIDozarivanie} alt="EtilenKhranenieIDozarivanie" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>EtilenKhranenieIDozarivanie</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_EtilenKhranenieIDozarivanie, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_IzmerenieMikroklimata: Story = {
  name: 'izmerenie-mikroklimata',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_IzmerenieMikroklimata} alt="IzmerenieMikroklimata" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>IzmerenieMikroklimata</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_IzmerenieMikroklimata, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_MikroklimatUsloviyaKhraneniya: Story = {
  name: 'mikroklimat-usloviya-khraneniya',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_MikroklimatUsloviyaKhraneniya} alt="MikroklimatUsloviyaKhraneniya" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>MikroklimatUsloviyaKhraneniya</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_MikroklimatUsloviyaKhraneniya, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_NevernyjMomentProdazhi: Story = {
  name: 'nevernyj-moment-prodazhi',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_NevernyjMomentProdazhi} alt="NevernyjMomentProdazhi" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>NevernyjMomentProdazhi</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_NevernyjMomentProdazhi, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_NevernyyMomentProdazhi: Story = {
  name: 'nevernyy-moment-prodazhi',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_NevernyyMomentProdazhi} alt="NevernyyMomentProdazhi" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>NevernyyMomentProdazhi</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_NevernyyMomentProdazhi, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Ozonirovanie: Story = {
  name: 'ozonirovanie',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Ozonirovanie} alt="Ozonirovanie" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Ozonirovanie</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Ozonirovanie, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_ParametryStoimosti: Story = {
  name: 'parametry-stoimosti',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_ParametryStoimosti} alt="ParametryStoimosti" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>ParametryStoimosti</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_ParametryStoimosti, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_ParametryUrozhaya: Story = {
  name: 'parametry-urozhaya',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_ParametryUrozhaya} alt="ParametryUrozhaya" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>ParametryUrozhaya</strong> · Analytics
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_ParametryUrozhaya, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Poteri1217: Story = {
  name: 'poteri-12-17',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Poteri1217} alt="Poteri1217" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Poteri1217</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Poteri1217, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_ProrastanieISozrevanie: Story = {
  name: 'prorastanie-i-sozrevanie',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_ProrastanieISozrevanie} alt="ProrastanieISozrevanie" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>ProrastanieISozrevanie</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_ProrastanieISozrevanie, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_SokhranostUrozhaya: Story = {
  name: 'sokhranost-urozhaya',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_SokhranostUrozhaya} alt="SokhranostUrozhaya" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>SokhranostUrozhaya</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_SokhranostUrozhaya, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_UsushkaIPorcha: Story = {
  name: 'usushka-i-porcha',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_UsushkaIPorcha} alt="UsushkaIPorcha" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>UsushkaIPorcha</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_UsushkaIPorcha, null, 2)}
      </pre>
    </div>
  ),
};
