/**
 * AUTO-GENERATED by Synaptik publish. Do not edit manually.
 * Import in product code: import { iconsBySlug } from './icons.manifest';
 */
import png_Co2PoteriMassyPriKhranenii from './co2-poteri-massy-pri-khranenii/icon.png';
import webp_Co2PoteriMassyPriKhranenii from './co2-poteri-massy-pri-khranenii/icon.webp';
import png_DannyeVPlatformu from './dannye-v-platformu/icon.png';
import webp_DannyeVPlatformu from './dannye-v-platformu/icon.webp';
import png_DinamikaPoMesyatsam from './dinamika-po-mesyatsam/icon.png';
import webp_DinamikaPoMesyatsam from './dinamika-po-mesyatsam/icon.webp';
import png_EtilenKhranenieIDozarivanie from './etilen-khranenie-i-dozarivanie/icon.png';
import webp_EtilenKhranenieIDozarivanie from './etilen-khranenie-i-dozarivanie/icon.webp';
import png_IzmerenieMikroklimata from './izmerenie-mikroklimata/icon.png';
import webp_IzmerenieMikroklimata from './izmerenie-mikroklimata/icon.webp';
import png_MikroklimatUsloviyaKhraneniya from './mikroklimat-usloviya-khraneniya/icon.png';
import webp_MikroklimatUsloviyaKhraneniya from './mikroklimat-usloviya-khraneniya/icon.webp';
import png_NevernyjMomentProdazhi from './nevernyj-moment-prodazhi/icon.png';
import webp_NevernyjMomentProdazhi from './nevernyj-moment-prodazhi/icon.webp';
import png_NevernyyMomentProdazhi from './nevernyy-moment-prodazhi/icon.png';
import webp_NevernyyMomentProdazhi from './nevernyy-moment-prodazhi/icon.webp';
import png_Ozonirovanie from './ozonirovanie/icon.png';
import webp_Ozonirovanie from './ozonirovanie/icon.webp';
import png_ParametryStoimosti from './parametry-stoimosti/icon.png';
import webp_ParametryStoimosti from './parametry-stoimosti/icon.webp';
import png_ParametryUrozhaya from './parametry-urozhaya/icon.png';
import webp_ParametryUrozhaya from './parametry-urozhaya/icon.webp';
import png_Poteri1217 from './poteri-12-17/icon.png';
import webp_Poteri1217 from './poteri-12-17/icon.webp';
import png_ProrastanieISozrevanie from './prorastanie-i-sozrevanie/icon.png';
import webp_ProrastanieISozrevanie from './prorastanie-i-sozrevanie/icon.webp';
import png_SokhranostUrozhaya from './sokhranost-urozhaya/icon.png';
import webp_SokhranostUrozhaya from './sokhranost-urozhaya/icon.webp';
import png_UsushkaIPorcha from './usushka-i-porcha/icon.png';
import webp_UsushkaIPorcha from './usushka-i-porcha/icon.webp';

export const projectSlug = 'agriculture-technology' as const;

export const iconsBySlug = {
  'co2-poteri-massy-pri-khranenii': {
    png: png_Co2PoteriMassyPriKhranenii,
    webp: webp_Co2PoteriMassyPriKhranenii,
    meta: {"name":"Co2PoteriMassyPriKhranenii","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"CO₂: потери массы при хранении","promptHash":"6dbacf4098df0f14","sessionId":"8e2f70a2","cardId":"co2-poteri-massy-pri-khranenii","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"co2-poteri-massy-pri-khranenii","publishedAt":"2026-06-02T08:20:26.555Z"} as const,
  },
  'dannye-v-platformu': {
    png: png_DannyeVPlatformu,
    webp: webp_DannyeVPlatformu,
    meta: {"name":"DannyeVPlatformu","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Данные в платформу","promptHash":"0e2d83118a2d726f","sessionId":"8e2f70a2","cardId":"dannye-v-platformu","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"dannye-v-platformu","publishedAt":"2026-06-02T08:22:14.367Z"} as const,
  },
  'dinamika-po-mesyatsam': {
    png: png_DinamikaPoMesyatsam,
    webp: webp_DinamikaPoMesyatsam,
    meta: {"name":"DinamikaPoMesyatsam","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Динамика по месяцам","promptHash":"78b2592561661d47","sessionId":"8e2f70a2","cardId":"dinamika-po-mesyatsam","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"dinamika-po-mesyatsam","publishedAt":"2026-06-02T08:20:20.773Z"} as const,
  },
  'etilen-khranenie-i-dozarivanie': {
    png: png_EtilenKhranenieIDozarivanie,
    webp: webp_EtilenKhranenieIDozarivanie,
    meta: {"name":"EtilenKhranenieIDozarivanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Этилен: хранение и дозаривание","promptHash":"72a65aa7a2d58c52","sessionId":"8e2f70a2","cardId":"etilen-khranenie-i-dozarivanie","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"etilen-khranenie-i-dozarivanie","publishedAt":"2026-06-02T08:20:23.569Z"} as const,
  },
  'izmerenie-mikroklimata': {
    png: png_IzmerenieMikroklimata,
    webp: webp_IzmerenieMikroklimata,
    meta: {"name":"IzmerenieMikroklimata","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Измерение микроклимата","promptHash":"6a66308e507223a7","sessionId":"8e2f70a2","cardId":"izmerenie-mikroklimata","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"izmerenie-mikroklimata","publishedAt":"2026-06-02T08:20:32.046Z"} as const,
  },
  'mikroklimat-usloviya-khraneniya': {
    png: png_MikroklimatUsloviyaKhraneniya,
    webp: webp_MikroklimatUsloviyaKhraneniya,
    meta: {"name":"MikroklimatUsloviyaKhraneniya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Микроклимат: условия хранения","promptHash":"1764106dc3399701","sessionId":"8e2f70a2","cardId":"mikroklimat-usloviya-khraneniya","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"mikroklimat-usloviya-khraneniya","publishedAt":"2026-06-02T08:20:29.627Z"} as const,
  },
  'nevernyj-moment-prodazhi': {
    png: png_NevernyjMomentProdazhi,
    webp: webp_NevernyjMomentProdazhi,
    meta: {"name":"NevernyjMomentProdazhi","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"96a17153fbb95099","sessionId":"1b081e1c","cardId":"nevernyj-moment-prodazhi","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"nevernyj-moment-prodazhi","publishedAt":"2026-06-02T11:30:54.288Z","falSeed":948839033} as const,
  },
  'nevernyy-moment-prodazhi': {
    png: png_NevernyyMomentProdazhi,
    webp: webp_NevernyyMomentProdazhi,
    meta: {"name":"NevernyyMomentProdazhi","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"ec0074111a2310f0","sessionId":"8e2f70a2","cardId":"nevernyy-moment-prodazhi","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"nevernyy-moment-prodazhi","publishedAt":"2026-06-02T08:20:12.057Z"} as const,
  },
  'ozonirovanie': {
    png: png_Ozonirovanie,
    webp: webp_Ozonirovanie,
    meta: {"name":"Ozonirovanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонирование","promptHash":"4289d7018fab046f","sessionId":"8e2f70a2","cardId":"ozonirovanie","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"ozonirovanie","publishedAt":"2026-06-02T08:21:19.094Z"} as const,
  },
  'parametry-stoimosti': {
    png: png_ParametryStoimosti,
    webp: webp_ParametryStoimosti,
    meta: {"name":"ParametryStoimosti","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры стоимости","promptHash":"d54ee12e4fe1f9ed","sessionId":"8e2f70a2","cardId":"parametry-stoimosti","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"parametry-stoimosti","publishedAt":"2026-06-02T08:20:17.826Z"} as const,
  },
  'parametry-urozhaya': {
    png: png_ParametryUrozhaya,
    webp: webp_ParametryUrozhaya,
    meta: {"name":"ParametryUrozhaya","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры урожая","promptHash":"230dbf24abbeec76","sessionId":"1b081e1c","cardId":"parametry-urozhaya","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"parametry-urozhaya","publishedAt":"2026-06-02T12:35:57.130Z","falSeed":111511914} as const,
  },
  'poteri-12-17': {
    png: png_Poteri1217,
    webp: webp_Poteri1217,
    meta: {"name":"Poteri1217","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Потери 12–17%","promptHash":"6fef87a24dd3d2ed","sessionId":"1b081e1c","cardId":"poteri-12-17","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"poteri-12-17","publishedAt":"2026-06-02T12:35:23.168Z","falSeed":742163273} as const,
  },
  'prorastanie-i-sozrevanie': {
    png: png_ProrastanieISozrevanie,
    webp: webp_ProrastanieISozrevanie,
    meta: {"name":"ProrastanieISozrevanie","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"C","sourceCard":"Прорастание и созревание","promptHash":"566cf0a0dad0ed35","sessionId":"1b081e1c","cardId":"prorastanie-i-sozrevanie","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"prorastanie-i-sozrevanie","publishedAt":"2026-06-02T14:22:39.367Z","falSeed":1557094316} as const,
  },
  'sokhranost-urozhaya': {
    png: png_SokhranostUrozhaya,
    webp: webp_SokhranostUrozhaya,
    meta: {"name":"SokhranostUrozhaya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сохранность урожая","promptHash":"d2f8f1a846858d90","sessionId":"8e2f70a2","cardId":"sokhranost-urozhaya","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"sokhranost-urozhaya","publishedAt":"2026-06-02T08:21:49.253Z"} as const,
  },
  'usushka-i-porcha': {
    png: png_UsushkaIPorcha,
    webp: webp_UsushkaIPorcha,
    meta: {"name":"UsushkaIPorcha","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"C","sourceCard":"Усушка и порча","promptHash":"5d4994773734b86c","sessionId":"1b081e1c","cardId":"usushka-i-porcha","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"usushka-i-porcha","publishedAt":"2026-06-02T12:35:34.447Z","falSeed":1904074101} as const,
  }
} as const;

export type GeneratedIconSlug = keyof typeof iconsBySlug;

export function getGeneratedIcon(slug: GeneratedIconSlug) {
  return iconsBySlug[slug];
}
