/**
 * AUTO-GENERATED by Synaptik publish. Do not edit manually.
 */
import type { StoryObj } from '@storybook/react';

export default {
  title: 'Generated Icons/agritech',
  parameters: { layout: 'padded' },
};

type Story = StoryObj;

import png_1217 from './12-17/icon.png';
import png_247 from './24-7/icon.png';
import png_6 from './6/icon.png';
import png_Card00904f5c23 from './card-00904f5c23/icon.png';
import png_Card343a0cd4df2 from './card-343a0cd4df/icon.png';
import png_Card35195232a8 from './card-35195232a8/icon.png';
import png_Card3ad7260126 from './card-3ad7260126/icon.png';
import png_Card40c9ccfc455 from './card-40c9ccfc45/icon.png';
import png_Card43a44f1f5a from './card-43a44f1f5a/icon.png';
import png_Card49337256ec from './card-49337256ec/icon.png';
import png_Card4e104b1c87 from './card-4e104b1c87/icon.png';
import png_Card52257113ea from './card-52257113ea/icon.png';
import png_Card538b6cb267 from './card-538b6cb267/icon.png';
import png_Card574a74e0f8 from './card-574a74e0f8/icon.png';
import png_Card5badf82455 from './card-5badf82455/icon.png';
import png_Card6abcafe7fa from './card-6abcafe7fa/icon.png';
import png_Card6e3b768aa8 from './card-6e3b768aa8/icon.png';
import png_Card7fe8be0e6a from './card-7fe8be0e6a/icon.png';
import png_Card83888742fd from './card-83888742fd/icon.png';
import png_Card8a270b4af6 from './card-8a270b4af6/icon.png';
import png_Card9068874dff from './card-9068874dff/icon.png';
import png_Card96f67de640 from './card-96f67de640/icon.png';
import png_CardAbb0ad49a9 from './card-abb0ad49a9/icon.png';
import png_CardB19e1359313 from './card-b19e135931/icon.png';
import png_CardC9df3dc074 from './card-c9df3dc074/icon.png';
import png_CardDa1bb29476 from './card-da1bb29476/icon.png';
import png_CardE5990fea2b from './card-e5990fea2b/icon.png';
import png_CardF15224e653 from './card-f15224e653/icon.png';
import png_Co24 from './co2/icon.png';

const META_1217 = {"name":"1217","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Потери 12–17%","promptHash":"9592fc873e1f98e6","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"12-17","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"12-17","publishedAt":"2026-06-03T11:31:45.973Z","falSeed":2004774315} as const;
const META_247 = {"name":"247","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"C","sourceCard":"Мониторинг 24/7","promptHash":"81da0c84cabaebc1","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"24-7","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"24-7","publishedAt":"2026-06-03T12:18:20.255Z","falSeed":909568762} as const;
const META_6 = {"name":"6","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"6 точек контроля и газовая среда","promptHash":"ca4688f22de392d5","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"6","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"6","publishedAt":"2026-06-03T12:17:24.654Z","falSeed":1434732761} as const;
const META_Card00904f5c23 = {"name":"Card00904f5c23","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Держите микроклимат под контролем","promptHash":"978a4f76acbd24ed","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-00904f5c23","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-00904f5c23","publishedAt":"2026-06-03T12:17:33.594Z","falSeed":1886341632} as const;
const META_Card343a0cd4df2 = {"name":"Card343a0cd4df2","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Измерение микроклимата","promptHash":"1a3da9c708a9ff73","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-343a0cd4df","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-343a0cd4df","publishedAt":"2026-06-03T11:43:32.328Z","falSeed":533113563} as const;
const META_Card35195232a8 = {"name":"Card35195232a8","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Динамика по месяцам","promptHash":"ce4f163e1784593d","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-35195232a8","blockId":"block-0e9a93ceb2","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"card-35195232a8","publishedAt":"2026-06-03T11:32:55.743Z","falSeed":1902317198} as const;
const META_Card3ad7260126 = {"name":"Card3ad7260126","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сохранность урожая","promptHash":"3a02ff6e8c376ff1","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-3ad7260126","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-3ad7260126","publishedAt":"2026-06-03T11:43:39.936Z","falSeed":400412718} as const;
const META_Card40c9ccfc455 = {"name":"Card40c9ccfc455","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Этилен: хранение и дозаривание","promptHash":"d2ecefab7ef06c00","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-40c9ccfc45","blockId":"block-c06e56e185","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"card-40c9ccfc45","publishedAt":"2026-06-03T11:43:10.779Z","falSeed":1751560715} as const;
const META_Card43a44f1f5a = {"name":"Card43a44f1f5a","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Участие в выставках","promptHash":"0563e62c03860356","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-43a44f1f5a","blockId":"block-25ff56b01f","blockTitle":"Подтверждения и отрасль","iconSlug":"card-43a44f1f5a","publishedAt":"2026-06-03T11:44:33.964Z","falSeed":694765724} as const;
const META_Card49337256ec = {"name":"Card49337256ec","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Данные в платформу","promptHash":"bab4d44ef1ee6e06","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-49337256ec","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-49337256ec","publishedAt":"2026-06-03T11:43:42.981Z","falSeed":2032074767} as const;
const META_Card4e104b1c87 = {"name":"Card4e104b1c87","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Интернет и архив","promptHash":"5d0eeaa118a8fac2","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-4e104b1c87","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-4e104b1c87","publishedAt":"2026-06-03T12:17:46.569Z","falSeed":1611372880} as const;
const META_Card52257113ea = {"name":"Card52257113ea","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Эко-технология без химикатов","promptHash":"34008ef6271412cf","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-52257113ea","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-52257113ea","publishedAt":"2026-06-03T11:44:25.674Z","falSeed":1222790394} as const;
const META_Card538b6cb267 = {"name":"Card538b6cb267","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонирование","promptHash":"9860d4e4e469913c","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-538b6cb267","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-538b6cb267","publishedAt":"2026-06-03T11:41:16.538Z","falSeed":410505139} as const;
const META_Card574a74e0f8 = {"name":"Card574a74e0f8","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"212db22449162d05","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-574a74e0f8","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"card-574a74e0f8","publishedAt":"2026-06-03T11:32:21.826Z","falSeed":472242135} as const;
const META_Card5badf82455 = {"name":"Card5badf82455","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры урожая","promptHash":"e8ea9af9b164cbcd","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-5badf82455","blockId":"block-0e9a93ceb2","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"card-5badf82455","publishedAt":"2026-06-03T11:32:33.598Z","falSeed":85844812} as const;
const META_Card6abcafe7fa = {"name":"Card6abcafe7fa","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Регулирование этилена","promptHash":"b1d9ccd07cd37eed","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-6abcafe7fa","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-6abcafe7fa","publishedAt":"2026-06-03T11:43:35.972Z","falSeed":264656231} as const;
const META_Card6e3b768aa8 = {"name":"Card6e3b768aa8","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры стоимости","promptHash":"af6ad8fbd4c58234","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-6e3b768aa8","blockId":"block-0e9a93ceb2","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"card-6e3b768aa8","publishedAt":"2026-06-03T11:32:43.216Z","falSeed":1381942992} as const;
const META_Card7fe8be0e6a = {"name":"Card7fe8be0e6a","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Контроль прорастания на хранении","promptHash":"3b7aef6a5fa4535e","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-7fe8be0e6a","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-7fe8be0e6a","publishedAt":"2026-06-03T11:43:52.948Z","falSeed":177295617} as const;
const META_Card83888742fd = {"name":"Card83888742fd","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Больше массы доходит до рынка","promptHash":"bf33c1192e6f21b5","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-83888742fd","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-83888742fd","publishedAt":"2026-06-03T11:44:22.572Z","falSeed":2081561225} as const;
const META_Card8a270b4af6 = {"name":"Card8a270b4af6","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Подготовка партии к продаже","promptHash":"3e5fa5d390a4b3a9","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-8a270b4af6","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-8a270b4af6","publishedAt":"2026-06-03T11:43:55.699Z","falSeed":1478850860} as const;
const META_Card9068874dff = {"name":"Card9068874dff","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонатор и топливо","promptHash":"d0588eef5feafb6b","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-9068874dff","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-9068874dff","publishedAt":"2026-06-03T12:18:31.859Z","falSeed":524581669} as const;
const META_Card96f67de640 = {"name":"Card96f67de640","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Усушка и порча","promptHash":"d96f9522b65b0326","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-96f67de640","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"card-96f67de640","publishedAt":"2026-06-03T11:31:57.588Z","falSeed":1580527662} as const;
const META_CardAbb0ad49a9 = {"name":"CardAbb0ad49a9","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Прорастание и созревание","promptHash":"afb0f468e41db5e5","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-abb0ad49a9","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"card-abb0ad49a9","publishedAt":"2026-06-03T11:32:11.319Z","falSeed":744630996} as const;
const META_CardB19e1359313 = {"name":"CardB19e1359313","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Микроклимат: условия хранения","promptHash":"0e9cc81bf9a8aa45","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-b19e135931","blockId":"block-c06e56e185","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"card-b19e135931","publishedAt":"2026-06-03T11:43:17.602Z","falSeed":1063056107} as const;
const META_CardC9df3dc074 = {"name":"CardC9df3dc074","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Автономность по топливу и электричеству","promptHash":"d2eb4687ff1904cd","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-c9df3dc074","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-c9df3dc074","publishedAt":"2026-06-03T12:17:15.013Z","falSeed":318243112} as const;
const META_CardDa1bb29476 = {"name":"CardDa1bb29476","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сколково и пилотные внедрения","promptHash":"f8fe5c6ff520cbdd","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-da1bb29476","blockId":"block-25ff56b01f","blockTitle":"Подтверждения и отрасль","iconSlug":"card-da1bb29476","publishedAt":"2026-06-03T11:44:31.163Z","falSeed":202988734} as const;
const META_CardE5990fea2b = {"name":"CardE5990fea2b","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Дозаривание перед реализацией","promptHash":"0dd1c830806b64b8","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-e5990fea2b","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-e5990fea2b","publishedAt":"2026-06-03T11:43:49.979Z","falSeed":691337060} as const;
const META_CardF15224e653 = {"name":"CardF15224e653","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Длительная сохранность","promptHash":"cdf35ad14ab9d0ec","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-f15224e653","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-f15224e653","publishedAt":"2026-06-03T11:43:47.028Z","falSeed":1725297231} as const;
const META_Co24 = {"name":"Co24","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"CO₂: потери массы при хранении","promptHash":"b78143491ca56dd6","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"co2","blockId":"block-c06e56e185","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"co2","publishedAt":"2026-06-03T11:43:14.522Z","falSeed":1978108343} as const;

const SRC_1217 = png_1217;
const SRC_247 = png_247;
const SRC_6 = png_6;
const SRC_Card00904f5c23 = png_Card00904f5c23;
const SRC_Card343a0cd4df2 = png_Card343a0cd4df2;
const SRC_Card35195232a8 = png_Card35195232a8;
const SRC_Card3ad7260126 = png_Card3ad7260126;
const SRC_Card40c9ccfc455 = png_Card40c9ccfc455;
const SRC_Card43a44f1f5a = png_Card43a44f1f5a;
const SRC_Card49337256ec = png_Card49337256ec;
const SRC_Card4e104b1c87 = png_Card4e104b1c87;
const SRC_Card52257113ea = png_Card52257113ea;
const SRC_Card538b6cb267 = png_Card538b6cb267;
const SRC_Card574a74e0f8 = png_Card574a74e0f8;
const SRC_Card5badf82455 = png_Card5badf82455;
const SRC_Card6abcafe7fa = png_Card6abcafe7fa;
const SRC_Card6e3b768aa8 = png_Card6e3b768aa8;
const SRC_Card7fe8be0e6a = png_Card7fe8be0e6a;
const SRC_Card83888742fd = png_Card83888742fd;
const SRC_Card8a270b4af6 = png_Card8a270b4af6;
const SRC_Card9068874dff = png_Card9068874dff;
const SRC_Card96f67de640 = png_Card96f67de640;
const SRC_CardAbb0ad49a9 = png_CardAbb0ad49a9;
const SRC_CardB19e1359313 = png_CardB19e1359313;
const SRC_CardC9df3dc074 = png_CardC9df3dc074;
const SRC_CardDa1bb29476 = png_CardDa1bb29476;
const SRC_CardE5990fea2b = png_CardE5990fea2b;
const SRC_CardF15224e653 = png_CardF15224e653;
const SRC_Co24 = png_Co24;

const ALL_ICON_ITEMS = [
  { name: '1217', slug: '12-17', src: SRC_1217, meta: META_1217 },
  { name: '247', slug: '24-7', src: SRC_247, meta: META_247 },
  { name: '6', slug: '6', src: SRC_6, meta: META_6 },
  { name: 'Card00904f5c23', slug: 'card-00904f5c23', src: SRC_Card00904f5c23, meta: META_Card00904f5c23 },
  { name: 'Card343a0cd4df2', slug: 'card-343a0cd4df', src: SRC_Card343a0cd4df2, meta: META_Card343a0cd4df2 },
  { name: 'Card35195232a8', slug: 'card-35195232a8', src: SRC_Card35195232a8, meta: META_Card35195232a8 },
  { name: 'Card3ad7260126', slug: 'card-3ad7260126', src: SRC_Card3ad7260126, meta: META_Card3ad7260126 },
  { name: 'Card40c9ccfc455', slug: 'card-40c9ccfc45', src: SRC_Card40c9ccfc455, meta: META_Card40c9ccfc455 },
  { name: 'Card43a44f1f5a', slug: 'card-43a44f1f5a', src: SRC_Card43a44f1f5a, meta: META_Card43a44f1f5a },
  { name: 'Card49337256ec', slug: 'card-49337256ec', src: SRC_Card49337256ec, meta: META_Card49337256ec },
  { name: 'Card4e104b1c87', slug: 'card-4e104b1c87', src: SRC_Card4e104b1c87, meta: META_Card4e104b1c87 },
  { name: 'Card52257113ea', slug: 'card-52257113ea', src: SRC_Card52257113ea, meta: META_Card52257113ea },
  { name: 'Card538b6cb267', slug: 'card-538b6cb267', src: SRC_Card538b6cb267, meta: META_Card538b6cb267 },
  { name: 'Card574a74e0f8', slug: 'card-574a74e0f8', src: SRC_Card574a74e0f8, meta: META_Card574a74e0f8 },
  { name: 'Card5badf82455', slug: 'card-5badf82455', src: SRC_Card5badf82455, meta: META_Card5badf82455 },
  { name: 'Card6abcafe7fa', slug: 'card-6abcafe7fa', src: SRC_Card6abcafe7fa, meta: META_Card6abcafe7fa },
  { name: 'Card6e3b768aa8', slug: 'card-6e3b768aa8', src: SRC_Card6e3b768aa8, meta: META_Card6e3b768aa8 },
  { name: 'Card7fe8be0e6a', slug: 'card-7fe8be0e6a', src: SRC_Card7fe8be0e6a, meta: META_Card7fe8be0e6a },
  { name: 'Card83888742fd', slug: 'card-83888742fd', src: SRC_Card83888742fd, meta: META_Card83888742fd },
  { name: 'Card8a270b4af6', slug: 'card-8a270b4af6', src: SRC_Card8a270b4af6, meta: META_Card8a270b4af6 },
  { name: 'Card9068874dff', slug: 'card-9068874dff', src: SRC_Card9068874dff, meta: META_Card9068874dff },
  { name: 'Card96f67de640', slug: 'card-96f67de640', src: SRC_Card96f67de640, meta: META_Card96f67de640 },
  { name: 'CardAbb0ad49a9', slug: 'card-abb0ad49a9', src: SRC_CardAbb0ad49a9, meta: META_CardAbb0ad49a9 },
  { name: 'CardB19e1359313', slug: 'card-b19e135931', src: SRC_CardB19e1359313, meta: META_CardB19e1359313 },
  { name: 'CardC9df3dc074', slug: 'card-c9df3dc074', src: SRC_CardC9df3dc074, meta: META_CardC9df3dc074 },
  { name: 'CardDa1bb29476', slug: 'card-da1bb29476', src: SRC_CardDa1bb29476, meta: META_CardDa1bb29476 },
  { name: 'CardE5990fea2b', slug: 'card-e5990fea2b', src: SRC_CardE5990fea2b, meta: META_CardE5990fea2b },
  { name: 'CardF15224e653', slug: 'card-f15224e653', src: SRC_CardF15224e653, meta: META_CardF15224e653 },
  { name: 'Co24', slug: 'co2', src: SRC_Co24, meta: META_Co24 }
] as const;

const BLOCK_0_ITEMS = [
  { slug: '12-17', src: SRC_1217, meta: META_1217 },
  { slug: 'card-574a74e0f8', src: SRC_Card574a74e0f8, meta: META_Card574a74e0f8 },
  { slug: 'card-96f67de640', src: SRC_Card96f67de640, meta: META_Card96f67de640 },
  { slug: 'card-abb0ad49a9', src: SRC_CardAbb0ad49a9, meta: META_CardAbb0ad49a9 },
] as const;

const BLOCK_1_ITEMS = [
  { slug: '24-7', src: SRC_247, meta: META_247 },
  { slug: '6', src: SRC_6, meta: META_6 },
  { slug: 'card-00904f5c23', src: SRC_Card00904f5c23, meta: META_Card00904f5c23 },
  { slug: 'card-4e104b1c87', src: SRC_Card4e104b1c87, meta: META_Card4e104b1c87 },
  { slug: 'card-9068874dff', src: SRC_Card9068874dff, meta: META_Card9068874dff },
  { slug: 'card-c9df3dc074', src: SRC_CardC9df3dc074, meta: META_CardC9df3dc074 },
] as const;

const BLOCK_2_ITEMS = [
  { slug: 'card-343a0cd4df', src: SRC_Card343a0cd4df2, meta: META_Card343a0cd4df2 },
  { slug: 'card-3ad7260126', src: SRC_Card3ad7260126, meta: META_Card3ad7260126 },
  { slug: 'card-49337256ec', src: SRC_Card49337256ec, meta: META_Card49337256ec },
  { slug: 'card-538b6cb267', src: SRC_Card538b6cb267, meta: META_Card538b6cb267 },
  { slug: 'card-6abcafe7fa', src: SRC_Card6abcafe7fa, meta: META_Card6abcafe7fa },
] as const;

const BLOCK_3_ITEMS = [
  { slug: 'card-35195232a8', src: SRC_Card35195232a8, meta: META_Card35195232a8 },
  { slug: 'card-5badf82455', src: SRC_Card5badf82455, meta: META_Card5badf82455 },
  { slug: 'card-6e3b768aa8', src: SRC_Card6e3b768aa8, meta: META_Card6e3b768aa8 },
] as const;

const BLOCK_4_ITEMS = [
  { slug: 'card-40c9ccfc45', src: SRC_Card40c9ccfc455, meta: META_Card40c9ccfc455 },
  { slug: 'card-b19e135931', src: SRC_CardB19e1359313, meta: META_CardB19e1359313 },
  { slug: 'co2', src: SRC_Co24, meta: META_Co24 },
] as const;

const BLOCK_5_ITEMS = [
  { slug: 'card-43a44f1f5a', src: SRC_Card43a44f1f5a, meta: META_Card43a44f1f5a },
  { slug: 'card-da1bb29476', src: SRC_CardDa1bb29476, meta: META_CardDa1bb29476 },
] as const;

const BLOCK_6_ITEMS = [
  { slug: 'card-52257113ea', src: SRC_Card52257113ea, meta: META_Card52257113ea },
  { slug: 'card-7fe8be0e6a', src: SRC_Card7fe8be0e6a, meta: META_Card7fe8be0e6a },
  { slug: 'card-83888742fd', src: SRC_Card83888742fd, meta: META_Card83888742fd },
  { slug: 'card-8a270b4af6', src: SRC_Card8a270b4af6, meta: META_Card8a270b4af6 },
  { slug: 'card-e5990fea2b', src: SRC_CardE5990fea2b, meta: META_CardE5990fea2b },
  { slug: 'card-f15224e653', src: SRC_CardF15224e653, meta: META_CardF15224e653 },
] as const;

export const AllIcons: Story = {
  name: 'All icons',
  render: () => {
    const items = ALL_ICON_ITEMS;
    return (
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16, padding: 16 }}>
        {items.map((item) => (
          <div key={item.name} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
            <img src={item.src} alt={item.name} width={80} height={80} style={{ objectFit: 'contain' }} />
            <div style={{ fontSize: 11, marginTop: 8 }}>{item.name}</div>
          </div>
        ))}
      </div>
    );
  },
};

export const ByBlocks: Story = {
  name: 'By blocks',
  render: () => (
    <div style={{ padding: 16 }}>
      <>
      <section key="block-0" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Отсутствие контроля = упущенная выгода</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_0_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-1" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Промышленный генератор этилена DAMIAT</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_1_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-2" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Как работает генератор</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_2_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-3" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Рассчитайте стоимость урожая и выгоду от хранения</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_3_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-4" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Контролируйте хранилище не выходя из дома</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_4_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-5" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Подтверждения и отрасль</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_5_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      <section key="block-6" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 14, margin: '0 0 12px', color: '#334155' }}>Польза генератора для хранилища</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16 }}>
          {BLOCK_6_ITEMS.map((item) => (
            <div key={item.slug} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
              <img src={item.src} alt={item.slug} width={80} height={80} style={{ objectFit: 'contain' }} />
              <div style={{ fontSize: 11, marginTop: 8 }}>{item.slug}</div>
            </div>
          ))}
        </div>
      </section>
      </>
    </div>
  ),
};

export const Icon_1217: Story = {
  name: '12-17',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_1217} alt="1217" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>1217</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_1217, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_247: Story = {
  name: '24-7',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_247} alt="247" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>247</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_247, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_6: Story = {
  name: '6',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_6} alt="6" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>6</strong> · Analytics
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_6, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card00904f5c23: Story = {
  name: 'card-00904f5c23',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card00904f5c23} alt="Card00904f5c23" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card00904f5c23</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card00904f5c23, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card343a0cd4df2: Story = {
  name: 'card-343a0cd4df',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card343a0cd4df2} alt="Card343a0cd4df2" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card343a0cd4df2</strong> · Product
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card343a0cd4df2, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card35195232a8: Story = {
  name: 'card-35195232a8',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card35195232a8} alt="Card35195232a8" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card35195232a8</strong> · Analytics
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card35195232a8, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card3ad7260126: Story = {
  name: 'card-3ad7260126',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card3ad7260126} alt="Card3ad7260126" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card3ad7260126</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card3ad7260126, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card40c9ccfc455: Story = {
  name: 'card-40c9ccfc45',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card40c9ccfc455} alt="Card40c9ccfc455" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card40c9ccfc455</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card40c9ccfc455, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card43a44f1f5a: Story = {
  name: 'card-43a44f1f5a',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card43a44f1f5a} alt="Card43a44f1f5a" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card43a44f1f5a</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card43a44f1f5a, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card49337256ec: Story = {
  name: 'card-49337256ec',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card49337256ec} alt="Card49337256ec" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card49337256ec</strong> · Product
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card49337256ec, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card4e104b1c87: Story = {
  name: 'card-4e104b1c87',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card4e104b1c87} alt="Card4e104b1c87" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card4e104b1c87</strong> · Product
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card4e104b1c87, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card52257113ea: Story = {
  name: 'card-52257113ea',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card52257113ea} alt="Card52257113ea" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card52257113ea</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card52257113ea, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card538b6cb267: Story = {
  name: 'card-538b6cb267',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card538b6cb267} alt="Card538b6cb267" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card538b6cb267</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card538b6cb267, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card574a74e0f8: Story = {
  name: 'card-574a74e0f8',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card574a74e0f8} alt="Card574a74e0f8" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card574a74e0f8</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card574a74e0f8, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card5badf82455: Story = {
  name: 'card-5badf82455',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card5badf82455} alt="Card5badf82455" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card5badf82455</strong> · Analytics
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card5badf82455, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card6abcafe7fa: Story = {
  name: 'card-6abcafe7fa',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card6abcafe7fa} alt="Card6abcafe7fa" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card6abcafe7fa</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card6abcafe7fa, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card6e3b768aa8: Story = {
  name: 'card-6e3b768aa8',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card6e3b768aa8} alt="Card6e3b768aa8" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card6e3b768aa8</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card6e3b768aa8, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card7fe8be0e6a: Story = {
  name: 'card-7fe8be0e6a',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card7fe8be0e6a} alt="Card7fe8be0e6a" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card7fe8be0e6a</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card7fe8be0e6a, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card83888742fd: Story = {
  name: 'card-83888742fd',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card83888742fd} alt="Card83888742fd" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card83888742fd</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card83888742fd, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card8a270b4af6: Story = {
  name: 'card-8a270b4af6',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card8a270b4af6} alt="Card8a270b4af6" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card8a270b4af6</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card8a270b4af6, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card9068874dff: Story = {
  name: 'card-9068874dff',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card9068874dff} alt="Card9068874dff" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card9068874dff</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card9068874dff, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Card96f67de640: Story = {
  name: 'card-96f67de640',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Card96f67de640} alt="Card96f67de640" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Card96f67de640</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Card96f67de640, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_CardAbb0ad49a9: Story = {
  name: 'card-abb0ad49a9',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_CardAbb0ad49a9} alt="CardAbb0ad49a9" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>CardAbb0ad49a9</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_CardAbb0ad49a9, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_CardB19e1359313: Story = {
  name: 'card-b19e135931',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_CardB19e1359313} alt="CardB19e1359313" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>CardB19e1359313</strong> · Product
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_CardB19e1359313, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_CardC9df3dc074: Story = {
  name: 'card-c9df3dc074',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_CardC9df3dc074} alt="CardC9df3dc074" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>CardC9df3dc074</strong> · Product
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_CardC9df3dc074, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_CardDa1bb29476: Story = {
  name: 'card-da1bb29476',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_CardDa1bb29476} alt="CardDa1bb29476" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>CardDa1bb29476</strong> · Business
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_CardDa1bb29476, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_CardE5990fea2b: Story = {
  name: 'card-e5990fea2b',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_CardE5990fea2b} alt="CardE5990fea2b" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>CardE5990fea2b</strong> · Performance
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_CardE5990fea2b, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_CardF15224e653: Story = {
  name: 'card-f15224e653',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_CardF15224e653} alt="CardF15224e653" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>CardF15224e653</strong> · Product
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_CardF15224e653, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Co24: Story = {
  name: 'co2',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={SRC_Co24} alt="Co24" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Co24</strong> · Analytics
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Co24, null, 2)}
      </pre>
    </div>
  ),
};
