/**
 * AUTO-GENERATED by Synaptik publish. Do not edit manually.
 * Import in product code: import { iconsBySlug } from './icons.manifest';
 */
import png_1217 from './12-17/icon.png';
import webp_1217 from './12-17/icon.webp';
import png_247 from './24-7/icon.png';
import webp_247 from './24-7/icon.webp';
import png_6 from './6/icon.png';
import webp_6 from './6/icon.webp';
import png_Card00904f5c23 from './card-00904f5c23/icon.png';
import webp_Card00904f5c23 from './card-00904f5c23/icon.webp';
import png_Card343a0cd4df2 from './card-343a0cd4df/icon.png';
import webp_Card343a0cd4df2 from './card-343a0cd4df/icon.webp';
import png_Card35195232a8 from './card-35195232a8/icon.png';
import webp_Card35195232a8 from './card-35195232a8/icon.webp';
import png_Card3ad7260126 from './card-3ad7260126/icon.png';
import webp_Card3ad7260126 from './card-3ad7260126/icon.webp';
import png_Card40c9ccfc455 from './card-40c9ccfc45/icon.png';
import webp_Card40c9ccfc455 from './card-40c9ccfc45/icon.webp';
import png_Card43a44f1f5a from './card-43a44f1f5a/icon.png';
import webp_Card43a44f1f5a from './card-43a44f1f5a/icon.webp';
import png_Card49337256ec from './card-49337256ec/icon.png';
import webp_Card49337256ec from './card-49337256ec/icon.webp';
import png_Card4e104b1c87 from './card-4e104b1c87/icon.png';
import webp_Card4e104b1c87 from './card-4e104b1c87/icon.webp';
import png_Card52257113ea from './card-52257113ea/icon.png';
import webp_Card52257113ea from './card-52257113ea/icon.webp';
import png_Card538b6cb267 from './card-538b6cb267/icon.png';
import webp_Card538b6cb267 from './card-538b6cb267/icon.webp';
import png_Card574a74e0f8 from './card-574a74e0f8/icon.png';
import webp_Card574a74e0f8 from './card-574a74e0f8/icon.webp';
import png_Card5badf82455 from './card-5badf82455/icon.png';
import webp_Card5badf82455 from './card-5badf82455/icon.webp';
import png_Card6abcafe7fa from './card-6abcafe7fa/icon.png';
import webp_Card6abcafe7fa from './card-6abcafe7fa/icon.webp';
import png_Card6e3b768aa8 from './card-6e3b768aa8/icon.png';
import webp_Card6e3b768aa8 from './card-6e3b768aa8/icon.webp';
import png_Card7fe8be0e6a from './card-7fe8be0e6a/icon.png';
import webp_Card7fe8be0e6a from './card-7fe8be0e6a/icon.webp';
import png_Card83888742fd from './card-83888742fd/icon.png';
import webp_Card83888742fd from './card-83888742fd/icon.webp';
import png_Card8a270b4af6 from './card-8a270b4af6/icon.png';
import webp_Card8a270b4af6 from './card-8a270b4af6/icon.webp';
import png_Card9068874dff from './card-9068874dff/icon.png';
import webp_Card9068874dff from './card-9068874dff/icon.webp';
import png_Card96f67de640 from './card-96f67de640/icon.png';
import webp_Card96f67de640 from './card-96f67de640/icon.webp';
import png_CardAbb0ad49a9 from './card-abb0ad49a9/icon.png';
import webp_CardAbb0ad49a9 from './card-abb0ad49a9/icon.webp';
import png_CardB19e1359313 from './card-b19e135931/icon.png';
import webp_CardB19e1359313 from './card-b19e135931/icon.webp';
import png_CardC9df3dc074 from './card-c9df3dc074/icon.png';
import webp_CardC9df3dc074 from './card-c9df3dc074/icon.webp';
import png_CardDa1bb29476 from './card-da1bb29476/icon.png';
import webp_CardDa1bb29476 from './card-da1bb29476/icon.webp';
import png_CardE5990fea2b from './card-e5990fea2b/icon.png';
import webp_CardE5990fea2b from './card-e5990fea2b/icon.webp';
import png_CardF15224e653 from './card-f15224e653/icon.png';
import webp_CardF15224e653 from './card-f15224e653/icon.webp';
import png_Co24 from './co2/icon.png';
import webp_Co24 from './co2/icon.webp';

export const projectSlug = 'agritech' as const;

export const iconsBySlug = {
  '12-17': {
    png: png_1217,
    webp: webp_1217,
    meta: {"name":"1217","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Потери 12–17%","promptHash":"9592fc873e1f98e6","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"12-17","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"12-17","publishedAt":"2026-06-03T11:31:45.973Z","falSeed":2004774315} as const,
  },
  '24-7': {
    png: png_247,
    webp: webp_247,
    meta: {"name":"247","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"C","sourceCard":"Мониторинг 24/7","promptHash":"81da0c84cabaebc1","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"24-7","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"24-7","publishedAt":"2026-06-03T12:18:20.255Z","falSeed":909568762} as const,
  },
  '6': {
    png: png_6,
    webp: webp_6,
    meta: {"name":"6","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"6 точек контроля и газовая среда","promptHash":"ca4688f22de392d5","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"6","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"6","publishedAt":"2026-06-03T12:17:24.654Z","falSeed":1434732761} as const,
  },
  'card-00904f5c23': {
    png: png_Card00904f5c23,
    webp: webp_Card00904f5c23,
    meta: {"name":"Card00904f5c23","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Держите микроклимат под контролем","promptHash":"978a4f76acbd24ed","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-00904f5c23","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-00904f5c23","publishedAt":"2026-06-03T12:17:33.594Z","falSeed":1886341632} as const,
  },
  'card-343a0cd4df': {
    png: png_Card343a0cd4df2,
    webp: webp_Card343a0cd4df2,
    meta: {"name":"Card343a0cd4df2","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Измерение микроклимата","promptHash":"1a3da9c708a9ff73","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-343a0cd4df","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-343a0cd4df","publishedAt":"2026-06-03T11:43:32.328Z","falSeed":533113563} as const,
  },
  'card-35195232a8': {
    png: png_Card35195232a8,
    webp: webp_Card35195232a8,
    meta: {"name":"Card35195232a8","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Динамика по месяцам","promptHash":"ce4f163e1784593d","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-35195232a8","blockId":"block-0e9a93ceb2","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"card-35195232a8","publishedAt":"2026-06-03T11:32:55.743Z","falSeed":1902317198} as const,
  },
  'card-3ad7260126': {
    png: png_Card3ad7260126,
    webp: webp_Card3ad7260126,
    meta: {"name":"Card3ad7260126","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сохранность урожая","promptHash":"3a02ff6e8c376ff1","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-3ad7260126","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-3ad7260126","publishedAt":"2026-06-03T11:43:39.936Z","falSeed":400412718} as const,
  },
  'card-40c9ccfc45': {
    png: png_Card40c9ccfc455,
    webp: webp_Card40c9ccfc455,
    meta: {"name":"Card40c9ccfc455","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Этилен: хранение и дозаривание","promptHash":"d2ecefab7ef06c00","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-40c9ccfc45","blockId":"block-c06e56e185","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"card-40c9ccfc45","publishedAt":"2026-06-03T11:43:10.779Z","falSeed":1751560715} as const,
  },
  'card-43a44f1f5a': {
    png: png_Card43a44f1f5a,
    webp: webp_Card43a44f1f5a,
    meta: {"name":"Card43a44f1f5a","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Участие в выставках","promptHash":"0563e62c03860356","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-43a44f1f5a","blockId":"block-25ff56b01f","blockTitle":"Подтверждения и отрасль","iconSlug":"card-43a44f1f5a","publishedAt":"2026-06-03T11:44:33.964Z","falSeed":694765724} as const,
  },
  'card-49337256ec': {
    png: png_Card49337256ec,
    webp: webp_Card49337256ec,
    meta: {"name":"Card49337256ec","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Данные в платформу","promptHash":"bab4d44ef1ee6e06","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-49337256ec","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-49337256ec","publishedAt":"2026-06-03T11:43:42.981Z","falSeed":2032074767} as const,
  },
  'card-4e104b1c87': {
    png: png_Card4e104b1c87,
    webp: webp_Card4e104b1c87,
    meta: {"name":"Card4e104b1c87","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Интернет и архив","promptHash":"5d0eeaa118a8fac2","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-4e104b1c87","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-4e104b1c87","publishedAt":"2026-06-03T12:17:46.569Z","falSeed":1611372880} as const,
  },
  'card-52257113ea': {
    png: png_Card52257113ea,
    webp: webp_Card52257113ea,
    meta: {"name":"Card52257113ea","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Эко-технология без химикатов","promptHash":"34008ef6271412cf","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-52257113ea","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-52257113ea","publishedAt":"2026-06-03T11:44:25.674Z","falSeed":1222790394} as const,
  },
  'card-538b6cb267': {
    png: png_Card538b6cb267,
    webp: webp_Card538b6cb267,
    meta: {"name":"Card538b6cb267","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонирование","promptHash":"9860d4e4e469913c","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-538b6cb267","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-538b6cb267","publishedAt":"2026-06-03T11:41:16.538Z","falSeed":410505139} as const,
  },
  'card-574a74e0f8': {
    png: png_Card574a74e0f8,
    webp: webp_Card574a74e0f8,
    meta: {"name":"Card574a74e0f8","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"212db22449162d05","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-574a74e0f8","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"card-574a74e0f8","publishedAt":"2026-06-03T11:32:21.826Z","falSeed":472242135} as const,
  },
  'card-5badf82455': {
    png: png_Card5badf82455,
    webp: webp_Card5badf82455,
    meta: {"name":"Card5badf82455","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры урожая","promptHash":"e8ea9af9b164cbcd","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-5badf82455","blockId":"block-0e9a93ceb2","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"card-5badf82455","publishedAt":"2026-06-03T11:32:33.598Z","falSeed":85844812} as const,
  },
  'card-6abcafe7fa': {
    png: png_Card6abcafe7fa,
    webp: webp_Card6abcafe7fa,
    meta: {"name":"Card6abcafe7fa","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Регулирование этилена","promptHash":"b1d9ccd07cd37eed","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-6abcafe7fa","blockId":"block-e13f580293","blockTitle":"Как работает генератор","iconSlug":"card-6abcafe7fa","publishedAt":"2026-06-03T11:43:35.972Z","falSeed":264656231} as const,
  },
  'card-6e3b768aa8': {
    png: png_Card6e3b768aa8,
    webp: webp_Card6e3b768aa8,
    meta: {"name":"Card6e3b768aa8","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры стоимости","promptHash":"af6ad8fbd4c58234","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-6e3b768aa8","blockId":"block-0e9a93ceb2","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"card-6e3b768aa8","publishedAt":"2026-06-03T11:32:43.216Z","falSeed":1381942992} as const,
  },
  'card-7fe8be0e6a': {
    png: png_Card7fe8be0e6a,
    webp: webp_Card7fe8be0e6a,
    meta: {"name":"Card7fe8be0e6a","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Контроль прорастания на хранении","promptHash":"3b7aef6a5fa4535e","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-7fe8be0e6a","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-7fe8be0e6a","publishedAt":"2026-06-03T11:43:52.948Z","falSeed":177295617} as const,
  },
  'card-83888742fd': {
    png: png_Card83888742fd,
    webp: webp_Card83888742fd,
    meta: {"name":"Card83888742fd","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Больше массы доходит до рынка","promptHash":"bf33c1192e6f21b5","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-83888742fd","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-83888742fd","publishedAt":"2026-06-03T11:44:22.572Z","falSeed":2081561225} as const,
  },
  'card-8a270b4af6': {
    png: png_Card8a270b4af6,
    webp: webp_Card8a270b4af6,
    meta: {"name":"Card8a270b4af6","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Подготовка партии к продаже","promptHash":"3e5fa5d390a4b3a9","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-8a270b4af6","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-8a270b4af6","publishedAt":"2026-06-03T11:43:55.699Z","falSeed":1478850860} as const,
  },
  'card-9068874dff': {
    png: png_Card9068874dff,
    webp: webp_Card9068874dff,
    meta: {"name":"Card9068874dff","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонатор и топливо","promptHash":"d0588eef5feafb6b","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-9068874dff","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-9068874dff","publishedAt":"2026-06-03T12:18:31.859Z","falSeed":524581669} as const,
  },
  'card-96f67de640': {
    png: png_Card96f67de640,
    webp: webp_Card96f67de640,
    meta: {"name":"Card96f67de640","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Усушка и порча","promptHash":"d96f9522b65b0326","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-96f67de640","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"card-96f67de640","publishedAt":"2026-06-03T11:31:57.588Z","falSeed":1580527662} as const,
  },
  'card-abb0ad49a9': {
    png: png_CardAbb0ad49a9,
    webp: webp_CardAbb0ad49a9,
    meta: {"name":"CardAbb0ad49a9","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Прорастание и созревание","promptHash":"afb0f468e41db5e5","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-abb0ad49a9","blockId":"block-41c3312b3b","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"card-abb0ad49a9","publishedAt":"2026-06-03T11:32:11.319Z","falSeed":744630996} as const,
  },
  'card-b19e135931': {
    png: png_CardB19e1359313,
    webp: webp_CardB19e1359313,
    meta: {"name":"CardB19e1359313","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Микроклимат: условия хранения","promptHash":"0e9cc81bf9a8aa45","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-b19e135931","blockId":"block-c06e56e185","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"card-b19e135931","publishedAt":"2026-06-03T11:43:17.602Z","falSeed":1063056107} as const,
  },
  'card-c9df3dc074': {
    png: png_CardC9df3dc074,
    webp: webp_CardC9df3dc074,
    meta: {"name":"CardC9df3dc074","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"B","sourceCard":"Автономность по топливу и электричеству","promptHash":"d2eb4687ff1904cd","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-c9df3dc074","blockId":"damiat","blockTitle":"Промышленный генератор этилена DAMIAT","iconSlug":"card-c9df3dc074","publishedAt":"2026-06-03T12:17:15.013Z","falSeed":318243112} as const,
  },
  'card-da1bb29476': {
    png: png_CardDa1bb29476,
    webp: webp_CardDa1bb29476,
    meta: {"name":"CardDa1bb29476","category":"Business","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сколково и пилотные внедрения","promptHash":"f8fe5c6ff520cbdd","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-da1bb29476","blockId":"block-25ff56b01f","blockTitle":"Подтверждения и отрасль","iconSlug":"card-da1bb29476","publishedAt":"2026-06-03T11:44:31.163Z","falSeed":202988734} as const,
  },
  'card-e5990fea2b': {
    png: png_CardE5990fea2b,
    webp: webp_CardE5990fea2b,
    meta: {"name":"CardE5990fea2b","category":"Performance","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Дозаривание перед реализацией","promptHash":"0dd1c830806b64b8","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-e5990fea2b","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-e5990fea2b","publishedAt":"2026-06-03T11:43:49.979Z","falSeed":691337060} as const,
  },
  'card-f15224e653': {
    png: png_CardF15224e653,
    webp: webp_CardF15224e653,
    meta: {"name":"CardF15224e653","category":"Product","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Длительная сохранность","promptHash":"cdf35ad14ab9d0ec","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"card-f15224e653","blockId":"block-8c14c662e2","blockTitle":"Польза генератора для хранилища","iconSlug":"card-f15224e653","publishedAt":"2026-06-03T11:43:47.028Z","falSeed":1725297231} as const,
  },
  'co2': {
    png: png_Co24,
    webp: webp_Co24,
    meta: {"name":"Co24","category":"Analytics","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"CO₂: потери массы при хранении","promptHash":"b78143491ca56dd6","iconSetStyleId":"isometric","sessionId":"03391fcf","cardId":"co2","blockId":"block-c06e56e185","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"co2","publishedAt":"2026-06-03T11:43:14.522Z","falSeed":1978108343} as const,
  }
} as const;

export type GeneratedIconSlug = keyof typeof iconsBySlug;

export function getGeneratedIcon(slug: GeneratedIconSlug) {
  return iconsBySlug[slug];
}
