/**
 * AUTO-GENERATED by Synaptik publish. Do not edit manually.
 */
import type { StoryObj } from '@storybook/react';

export default {
  title: 'Generated Icons/agriculture-technology',
  parameters: { layout: 'padded' },
};

type Story = StoryObj;

const META_Co2PoteriMassyPriKhranenii = {"name":"Co2PoteriMassyPriKhranenii","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"CO₂: потери массы при хранении","promptHash":"6dbacf4098df0f14","sessionId":"8e2f70a2","cardId":"co2-poteri-massy-pri-khranenii","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"co2-poteri-massy-pri-khranenii","publishedAt":"2026-06-02T08:20:26.555Z"} as const;
const META_DannyeVPlatformu = {"name":"DannyeVPlatformu","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Данные в платформу","promptHash":"0e2d83118a2d726f","sessionId":"8e2f70a2","cardId":"dannye-v-platformu","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"dannye-v-platformu","publishedAt":"2026-06-02T08:22:14.367Z"} as const;
const META_DinamikaPoMesyatsam = {"name":"DinamikaPoMesyatsam","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Динамика по месяцам","promptHash":"78b2592561661d47","sessionId":"8e2f70a2","cardId":"dinamika-po-mesyatsam","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"dinamika-po-mesyatsam","publishedAt":"2026-06-02T08:20:20.773Z"} as const;
const META_EtilenKhranenieIDozarivanie = {"name":"EtilenKhranenieIDozarivanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Этилен: хранение и дозаривание","promptHash":"72a65aa7a2d58c52","sessionId":"8e2f70a2","cardId":"etilen-khranenie-i-dozarivanie","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"etilen-khranenie-i-dozarivanie","publishedAt":"2026-06-02T08:20:23.569Z"} as const;
const META_IzmerenieMikroklimata = {"name":"IzmerenieMikroklimata","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Измерение микроклимата","promptHash":"6a66308e507223a7","sessionId":"8e2f70a2","cardId":"izmerenie-mikroklimata","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"izmerenie-mikroklimata","publishedAt":"2026-06-02T08:20:32.046Z"} as const;
const META_MikroklimatUsloviyaKhraneniya = {"name":"MikroklimatUsloviyaKhraneniya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Микроклимат: условия хранения","promptHash":"1764106dc3399701","sessionId":"8e2f70a2","cardId":"mikroklimat-usloviya-khraneniya","blockId":"icon","blockTitle":"Контролируйте хранилище не выходя из дома","iconSlug":"mikroklimat-usloviya-khraneniya","publishedAt":"2026-06-02T08:20:29.627Z"} as const;
const META_NevernyyMomentProdazhi = {"name":"NevernyyMomentProdazhi","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Неверный момент продажи","promptHash":"ec0074111a2310f0","sessionId":"8e2f70a2","cardId":"nevernyy-moment-prodazhi","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"nevernyy-moment-prodazhi","publishedAt":"2026-06-02T08:20:12.057Z"} as const;
const META_Ozonirovanie = {"name":"Ozonirovanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Озонирование","promptHash":"4289d7018fab046f","sessionId":"8e2f70a2","cardId":"ozonirovanie","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"ozonirovanie","publishedAt":"2026-06-02T08:21:19.094Z"} as const;
const META_ParametryStoimosti = {"name":"ParametryStoimosti","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры стоимости","promptHash":"d54ee12e4fe1f9ed","sessionId":"8e2f70a2","cardId":"parametry-stoimosti","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"parametry-stoimosti","publishedAt":"2026-06-02T08:20:17.826Z"} as const;
const META_ParametryUrozhaya = {"name":"ParametryUrozhaya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Параметры урожая","promptHash":"9c638f65fb54fd8f","sessionId":"8e2f70a2","cardId":"parametry-urozhaya","blockId":"icon","blockTitle":"Рассчитайте стоимость урожая и выгоду от хранения","iconSlug":"parametry-urozhaya","publishedAt":"2026-06-02T08:20:14.439Z"} as const;
const META_Poteri1217 = {"name":"Poteri1217","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Потери 12–17%","promptHash":"4b203e7177ffe370","sessionId":"8e2f70a2","cardId":"poteri-12-17","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"poteri-12-17","publishedAt":"2026-06-02T08:29:41.755Z"} as const;
const META_ProrastanieISozrevanie = {"name":"ProrastanieISozrevanie","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Прорастание и созревание","promptHash":"f836f5fe8f2ace67","sessionId":"8e2f70a2","cardId":"prorastanie-i-sozrevanie","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"prorastanie-i-sozrevanie","publishedAt":"2026-06-02T08:20:01.048Z"} as const;
const META_SokhranostUrozhaya = {"name":"SokhranostUrozhaya","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Сохранность урожая","promptHash":"d2f8f1a846858d90","sessionId":"8e2f70a2","cardId":"sokhranost-urozhaya","blockId":"icon","blockTitle":"Как работает генератор","iconSlug":"sokhranost-urozhaya","publishedAt":"2026-06-02T08:21:49.253Z"} as const;
const META_UsushkaIPorcha = {"name":"UsushkaIPorcha","category":"AgroTech","style":"Damiat","createdBy":"AI Icon Builder","conceptId":"A","sourceCard":"Усушка и порча","promptHash":"99d5d44848f74abb","sessionId":"8e2f70a2","cardId":"usushka-i-porcha","blockId":"icon","blockTitle":"Отсутствие контроля = упущенная выгода","iconSlug":"usushka-i-porcha","publishedAt":"2026-06-02T08:20:05.903Z"} as const;

export const AllIcons: Story = {
  name: 'All icons',
  render: () => {
    const items = [
        { name: 'Co2PoteriMassyPriKhranenii', src: new URL('./co2-poteri-massy-pri-khranenii/icon.png', import.meta.url).href, meta: META_Co2PoteriMassyPriKhranenii },
        { name: 'DannyeVPlatformu', src: new URL('./dannye-v-platformu/icon.png', import.meta.url).href, meta: META_DannyeVPlatformu },
        { name: 'DinamikaPoMesyatsam', src: new URL('./dinamika-po-mesyatsam/icon.png', import.meta.url).href, meta: META_DinamikaPoMesyatsam },
        { name: 'EtilenKhranenieIDozarivanie', src: new URL('./etilen-khranenie-i-dozarivanie/icon.png', import.meta.url).href, meta: META_EtilenKhranenieIDozarivanie },
        { name: 'IzmerenieMikroklimata', src: new URL('./izmerenie-mikroklimata/icon.png', import.meta.url).href, meta: META_IzmerenieMikroklimata },
        { name: 'MikroklimatUsloviyaKhraneniya', src: new URL('./mikroklimat-usloviya-khraneniya/icon.png', import.meta.url).href, meta: META_MikroklimatUsloviyaKhraneniya },
        { name: 'NevernyyMomentProdazhi', src: new URL('./nevernyy-moment-prodazhi/icon.png', import.meta.url).href, meta: META_NevernyyMomentProdazhi },
        { name: 'Ozonirovanie', src: new URL('./ozonirovanie/icon.png', import.meta.url).href, meta: META_Ozonirovanie },
        { name: 'ParametryStoimosti', src: new URL('./parametry-stoimosti/icon.png', import.meta.url).href, meta: META_ParametryStoimosti },
        { name: 'ParametryUrozhaya', src: new URL('./parametry-urozhaya/icon.png', import.meta.url).href, meta: META_ParametryUrozhaya },
        { name: 'Poteri1217', src: new URL('./poteri-12-17/icon.png', import.meta.url).href, meta: META_Poteri1217 },
        { name: 'ProrastanieISozrevanie', src: new URL('./prorastanie-i-sozrevanie/icon.png', import.meta.url).href, meta: META_ProrastanieISozrevanie },
        { name: 'SokhranostUrozhaya', src: new URL('./sokhranost-urozhaya/icon.png', import.meta.url).href, meta: META_SokhranostUrozhaya },
        { name: 'UsushkaIPorcha', src: new URL('./usushka-i-porcha/icon.png', import.meta.url).href, meta: META_UsushkaIPorcha }
    ];
    return (
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 16, padding: 16 }}>
        {items.map((item) => (
          <div key={item.name} style={{ textAlign: 'center', padding: 12, border: '1px solid #e2e8f0', borderRadius: 8 }}>
            <img src={item.src} alt={item.name} width={80} height={80} style={{ objectFit: 'contain' }} />
            <div style={{ fontSize: 11, marginTop: 8 }}>{item.name}</div>
          </div>
        ))}
      </div>
    );
  },
};

export const Icon_Co2PoteriMassyPriKhranenii: Story = {
  name: 'co2-poteri-massy-pri-khranenii',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./co2-poteri-massy-pri-khranenii/icon.png', import.meta.url).href} alt="Co2PoteriMassyPriKhranenii" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Co2PoteriMassyPriKhranenii</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Co2PoteriMassyPriKhranenii, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_DannyeVPlatformu: Story = {
  name: 'dannye-v-platformu',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./dannye-v-platformu/icon.png', import.meta.url).href} alt="DannyeVPlatformu" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>DannyeVPlatformu</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_DannyeVPlatformu, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_DinamikaPoMesyatsam: Story = {
  name: 'dinamika-po-mesyatsam',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./dinamika-po-mesyatsam/icon.png', import.meta.url).href} alt="DinamikaPoMesyatsam" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>DinamikaPoMesyatsam</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_DinamikaPoMesyatsam, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_EtilenKhranenieIDozarivanie: Story = {
  name: 'etilen-khranenie-i-dozarivanie',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./etilen-khranenie-i-dozarivanie/icon.png', import.meta.url).href} alt="EtilenKhranenieIDozarivanie" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>EtilenKhranenieIDozarivanie</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_EtilenKhranenieIDozarivanie, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_IzmerenieMikroklimata: Story = {
  name: 'izmerenie-mikroklimata',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./izmerenie-mikroklimata/icon.png', import.meta.url).href} alt="IzmerenieMikroklimata" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>IzmerenieMikroklimata</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_IzmerenieMikroklimata, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_MikroklimatUsloviyaKhraneniya: Story = {
  name: 'mikroklimat-usloviya-khraneniya',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./mikroklimat-usloviya-khraneniya/icon.png', import.meta.url).href} alt="MikroklimatUsloviyaKhraneniya" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>MikroklimatUsloviyaKhraneniya</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_MikroklimatUsloviyaKhraneniya, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_NevernyyMomentProdazhi: Story = {
  name: 'nevernyy-moment-prodazhi',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./nevernyy-moment-prodazhi/icon.png', import.meta.url).href} alt="NevernyyMomentProdazhi" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>NevernyyMomentProdazhi</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_NevernyyMomentProdazhi, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Ozonirovanie: Story = {
  name: 'ozonirovanie',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./ozonirovanie/icon.png', import.meta.url).href} alt="Ozonirovanie" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Ozonirovanie</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Ozonirovanie, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_ParametryStoimosti: Story = {
  name: 'parametry-stoimosti',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./parametry-stoimosti/icon.png', import.meta.url).href} alt="ParametryStoimosti" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>ParametryStoimosti</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_ParametryStoimosti, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_ParametryUrozhaya: Story = {
  name: 'parametry-urozhaya',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./parametry-urozhaya/icon.png', import.meta.url).href} alt="ParametryUrozhaya" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>ParametryUrozhaya</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_ParametryUrozhaya, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_Poteri1217: Story = {
  name: 'poteri-12-17',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./poteri-12-17/icon.png', import.meta.url).href} alt="Poteri1217" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>Poteri1217</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_Poteri1217, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_ProrastanieISozrevanie: Story = {
  name: 'prorastanie-i-sozrevanie',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./prorastanie-i-sozrevanie/icon.png', import.meta.url).href} alt="ProrastanieISozrevanie" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>ProrastanieISozrevanie</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_ProrastanieISozrevanie, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_SokhranostUrozhaya: Story = {
  name: 'sokhranost-urozhaya',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./sokhranost-urozhaya/icon.png', import.meta.url).href} alt="SokhranostUrozhaya" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>SokhranostUrozhaya</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_SokhranostUrozhaya, null, 2)}
      </pre>
    </div>
  ),
};

export const Icon_UsushkaIPorcha: Story = {
  name: 'usushka-i-porcha',
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 16 }}>
      <img src={new URL('./usushka-i-porcha/icon.png', import.meta.url).href} alt="UsushkaIPorcha" width={128} height={128} style={{ objectFit: 'contain' }} />
      <div style={{ fontSize: 12, color: '#64748b' }}>
        <strong>UsushkaIPorcha</strong> · AgroTech
      </div>
      <pre style={{ fontSize: 10, background: '#f1f5f9', padding: 8, borderRadius: 8, maxWidth: 320 }}>
        {JSON.stringify(META_UsushkaIPorcha, null, 2)}
      </pre>
    </div>
  ),
};
