/**
 * AUTO-GENERATED by Synaptik publish. Index content lives in ./SynaptikIndex.tsx
 */
import type { StoryObj } from '@storybook/react';
import { SynaptikIndex } from './SynaptikIndex';

export default {
  title: 'Generated Icons',
  parameters: { layout: 'padded' },
};

type Story = StoryObj;
const PROJECT_SLUGS = ["agriculture-technology","agritech"] as const;

export const Index: Story = {
  name: 'Synaptik guide',
  render: () => <SynaptikIndex projectSlugs={[...PROJECT_SLUGS]} />,
};